# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Transport to OneDrive

on:
  workflow_dispatch:
  schedule:
     - cron: '0 */4 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run
      env:
        client_id: ${{ secrets.CLIENT_ID }}
        tenant_id: ${{ secrets.TENANT_ID }}
        secret: ${{ secrets.SECRET }}
        user_id: ${{ secrets.USER_ID }}
        baidu_client_id: ${{ secrets.BAIDU_CLIENT_ID }}
        baidu_client_secret: ${{ secrets.BAIDU_CLIENT_SECRET }}
        refresh_token_key: ${{ secrets.REFRESH_TOKEN_KEY }}
        refresh_token_associated_data: ${{ secrets.REFRESH_TOKEN_ASSOCIATED_DATA }}
      run: |
        python main.py baidu_to_onedrive
